language: php
php:
- 7.1
- 7.2
- 7.3
- 7.4
env:
  matrix:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""
before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
script:
- vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
- vendor/bin/phpcs --standard=PSR2 ./src
after_script:
- php vendor/bin/php-coveralls -v
notifications:
  slack:
    secure: Qm00aimcttvA63wpArRqKH/H0Fft12ecf1TbN0BWjzxdiwjuqgUhF5k2byxxfaRly/BRK98CrAdjYym1JuCvk4yUYbYkN5blz023Kz73Xlk7K60pIqS7smtpKC2UG14gbjLJHtYH7fW7iEiUSI43TuMgGtthZUmQfaBPxKH19RIyfDuC4onYKF2CuH7jlxDoDrgJl7jago4VWXrszlcnYgFkK1+cbFzk4bV73Np67/3rgGU10hMdmncGKMpVE5+92moVInNd3zbPsxYNEeNPMLmdPorid2St+g7iJ9YEJXdklUXRRwgJ6cwNJzyKGlxo2OiHBk8esMTQ8HYi10tpJGDcKOPWLY//x1pw5qCf1TVKIxaTAWctI9UWZZ1CHJps7VKwscAW3gh++NIgqriaF/WgzhiSzS8qytrMoCmZ4GCsFqsgAruWORO+zawORMNDydZoNOSe8TrKaLGAVCAeFrbcyIc6OER7ACs66fNPP2/7u3QvwKfKyLo+IL5ommdSr1wCUbzf8rTdNYT0IFUpWSOY1b3eEAejgjgWM7GPQUGx7upXPYWCICULLRMYEWXl7qgwdzyMuHS/Fff8L51uqc2HJYUXmylZMFcBeYR+yv7dWiX9XrQ5WpA3m2OanEYPHTMnL6NwHxNPpMm692puyNzOiXJNnvzLUxJaeQ5siTs=
