name: CI

on:
    push:
        branches: [master]
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    ci:
        name: PHP ${{ matrix.php }} ${{ matrix.dependency_type }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ["8.3", "8.4", "8.5"]
                dependency_type: ["stable", "lowest"]
                include:
                    - dependency_type: "stable"
                      composer_flags: "--no-interaction --no-progress"
                    - dependency_type: "lowest"
                      composer_flags: "--no-interaction --no-progress --prefer-lowest"

        steps:
            - uses: actions/checkout@v6

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: xdebug, curl
                  tools: composer

            - name: Install dependencies
              run: composer update ${{ matrix.composer_flags }}

            - name: Run lint
              run: ./vendor/bin/phpcs

            - name: Run tests
              run: ./vendor/bin/phpunit --coverage-cobertura ./cobertura.xml
              env:
                  XDEBUG_MODE: coverage

            - name: Code Coverage Report
              if: matrix.php == '8.3' && matrix.dependency_type == 'stable'
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                  filename: ./cobertura.xml
                  badge: true
                  fail_below_min: true
                  format: markdown
                  hide_branch_rate: false
                  hide_complexity: true
                  indicators: true
                  output: both
                  thresholds: "60 80"

            - name: Write Coverage to Job Summary
              if: matrix.php == '8.3' && matrix.dependency_type == 'stable'
              run: |
                  echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
                  cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
