name: CI

on: [push, pull_request]

jobs:
    ci:
        name: PHP ${{ matrix.php }} ${{ matrix.dependency_type }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ["8.3", "8.4", "8.5"]
                dependency_type: ["stable", "lowest"]
                include:
                    - dependency_type: "stable"
                      composer_flags: "--no-interaction --no-progress"
                    - dependency_type: "lowest"
                      composer_flags: "--no-interaction --no-progress --prefer-lowest"

        steps:
            - uses: actions/checkout@v6

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: xdebug, mbstring, openssl
                  tools: composer

            - name: Configure Git
              run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

            - name: DEBUG
              run: composer update guzzlehttp/guzzle:7.10.0 --with-all-dependencies -vvv

            - name: Install dependencies
              run: composer update ${{ matrix.composer_flags }}

            - name: Run lint
              run: composer run lint

            - name: Run tests
              run: ./vendor/bin/phpunit--coverage-cobertura ./cobertura.xml
              env:
                  XDEBUG_MODE: coverage

            # - name: Code Coverage Report
            #   if: matrix.php == '8.3' && matrix.dependency_type == 'stable'
            #   uses: irongut/CodeCoverageSummary@v1.3.0
            #   with:
            #       filename: ./cobertura.xml
            #       badge: true
            #       fail_below_min: true
            #       format: markdown
            #       hide_branch_rate: false
            #       hide_complexity: true
            #       indicators: true
            #       output: both
            #       thresholds: "60 80"

            # - name: Add Coverage PR Comment
            #   if: github.event_name == 'pull_request' && matrix.php == '8.3' && matrix.dependency_type == 'stable'
            #   uses: marocchino/sticky-pull-request-comment@v2
            #   with:
            #       recreate: true
            #       path: code-coverage-results.md
